# Standard themes
#theme: jekyll-theme-minimal
# theme: jekyll-theme-midnight
# theme: jekyll-theme-primer
# theme: jekyll-theme-slate
# theme: jekyll-theme-hacker
# theme: jekyll-theme-architect
# theme: jekyll-theme-cayman

# Remote themes
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one


title: CE-QUAL-W2
description: Two-dimensional, laterally averaged, hydrodynamic and water quality model
baseurl: ""
url: "https://ce-qual-w2-erdc.github.io"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Documentation
    url: /documentation/
  - title: Downloads
    url: /downloads/
  - title: Examples
    url: /examples/
  - title: Publications
    url: /publications/
  - title: Support
    url: /support/

# Build settings
markdown: kramdown

# Exclude files from build
exclude:
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
